# Generated by Django 5.0.7 on 2024-07-15 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Post",
        ),
    ]
